### ISSUE TITLE
TODO для второго релиза

### ISSUE THREAD

**Issue by danilstoyanov** [uz0/pick.gg#200]
### Бэкенд
- [x] Сделать виртуальное поле isPrepared для турниров (есть отдельный issue)
- [x] Сделать виартуальное поля isUsed для наград (во избежание выбора одной и той же награды в качестве приза в паралелльно идущих турнирах)
- [x] Сделать подсчёт результатов для summoners и viewers после каждого матча
- [x] Добавить поддержку добавления результатов, путём загрузки html страницы из истории матчей
- [x] Сделать ручку для финализации турнира (окончательный подсчёт всех баллов, распределение ревардов)
- [x] Доделать бэкенд для формирования рейтинга стримеров, вьюверов и призывателей
- [x] Переименовать урл для принятия участие в турнире в качестве зрителя (view на forecast заменить)

#### Страница турниры
- [x] Используя поле isPrepared, добавить соответствующий статус в виджет с информацией о турнире.
- [x] Сделать виджет для ревардов турнира (картинка с ревардом, и за какое место даётся)
- [x] Добавить валидацию в форму добавления ревардов (нельзя один и тот же ревард выбрать в качестве награды несколько раз. На каждое место - по реварду. Также, использя виртуальное поле isUsed чекать, что ревард является призом в **одном** турнире)
- [x] Проверить, чтобы добавление ревардов работало без сбоев.
- [x] Доделать редактирование матчей
- [x]  Сделать везде вывод очков (саммонеры, вьюверы)
- [x] Когда матчи идут, помечать активный матч каким-либо образом. Проверить логику с состоянием матчей (isActive, startedAt, endAt, updatedAt)
- [x] Убедиться, что незарегистрированный пользователь может заходить на страницу турнира
- [x]  Доработать и протестировать логику работы с Applicants
#### Страница рейтинг
- [x] Убрать заглушки, интегрировав фронтенд с бэкендом рейтинга
- [x] Проверить, что незарегистрированный пользователь может смотреть рейтинг
- [ ] Сделать вкладки для анонсов и своих турниров
![image](https://user-images.githubusercontent.com/18240896/61869375-251dd780-aee4-11e9-9ef3-f3fecf5bfdac.png)

**ЧТО КРИТИЧНО**
- [x] после авторизации никаких дополнительных уведомлений
- [x] реварды Cannot read property 'forEach' of undefined и в целом админка - боль
- [x] обновления матчей должны работать?
- [x]  добавление реварда
- [x] мобильная версия списка турниров и страницы турнира (котик?)
- [x] Price: $ 0 (бесплатно)
- [x] перейти по ссылке на турнир БУДУЧИ НЕ АВТОРИЗОВАННОЙ и после РЕГИСТРАЦИИ попасть автоматом на нужный турнир
- [x] заполнить данные турнира (счет \ результаты) и финализировать, чтобы участники получили награды!
- [x] сценарий с аппликантами должен работать! (как призыватель я могу подать заявку на участие и как стример я должна иметь возможность принять эту заявку)
- [x] после авторизации (если принимаем заявки на призывателей) показываем предупреждение со ссылкой заполнить, на странице редактирования профиля делаем большую подсказку, типо введите имя презывателя на RU сервере (хардкодеее)
- [x] сценарий с конкурсами прогнозов, ОБЯЗАТЕЛЬНО КРУПНО В БЛОКЕ ПРОГНОЗОВ ДОПИСАТЬ ЧТО КОНКУРС ПРОГНОЗОВ НЕДОСТУПЕН (если он не доступен) и подписать КОГДА он будет доступен!
- [ ] чекнуть что стоит яндекс метрика и кнопки прописаны на события (для зрителей)
- [x] проверить валидацию полей в формах. Минимальное количество символов для начала.

**Comment by danilstoyanov** [comment]
также карточки турнира можно оформить вдохновившись рефом:
![image](https://user-images.githubusercontent.com/18240896/61904178-f4af5b00-af2e-11e9-99d6-cc2464ef6c89.png)

**Comment by dcversus** [comment]
Важная ремарка! Если юзер принял участие как саммонер или он стример, то он НЕ МОЖЕТ делать прогнозы... плез учти))

**Comment by danilstoyanov** [comment]
Аппликантов видит только стример
